# This file is part of walt
# https://github.com/scorphus/walt

# Licensed under the BSD-3-Clause license:
# https://opensource.org/licenses/BSD-3-Clause
# Copyright (c) 2021, Pablo S. Blum de Aguiar <scorphus@gmail.com>

name: Python
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
          - 3.10-dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        id: deps_cache
        with:
          path: |
            ${{ env.pythonLocation}}/lib/*/site-packages/*
            ${{ env.pythonLocation}}/bin/*
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install package and dependencies
        run: make setup-ci
      - name: Run tests
        run: make test
      - name: Send coverage stats to Codecov
        if: matrix.python-version == '3.9'
        run: bash <(curl -s https://codecov.io/bash)
      - name: Run linters and check formatting
        if: matrix.python-version == '3.9'
        run: make lint
